"""Resume + template + style -> Word (.docx) bytes, in memory.

Word cannot use the self-hosted web fonts, so each template maps to a font that ships with
Windows, macOS and Google Docs. Section bodies are the same HTML the PDF uses (generated by
resume.py, so only a small, known set of tags), turned into real Word paragraphs and lists.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from html.parser import HTMLParser
from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_TAB_ALIGNMENT
from docx.opc.constants import RELATIONSHIP_TYPE as RT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Emu, Inches, Mm, Pt, RGBColor
from docx.text.paragraph import Paragraph

from render import ACCENTS, PAGE_SIZES, Style, available_templates
from resume import Resume

TEXT = RGBColor(0x1C, 0x1C, 0x1A)
MUTED = RGBColor(0x5C, 0x5C, 0x58)
ALIGN = {"left": WD_ALIGN_PARAGRAPH.LEFT, "center": WD_ALIGN_PARAGRAPH.CENTER, "right": WD_ALIGN_PARAGRAPH.RIGHT}
DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"


@dataclass(frozen=True)
class Look:
    """The Word version of each print template."""
    font: str
    size: float
    name_size: float
    accent: str
    header_align: str
    name_accent: bool = False
    headline_accent: bool = False
    title_caps: bool = False
    title_bold: bool = True
    title_size: float = 11
    title_rule: str = ""  # "below", "above" or ""
    header_rule: bool = False
    italic_meta: bool = False  # dates and the organisation line in italics


LOOKS = {
    "classic": Look("Georgia", 10, 20, "1C1C1A", "center", name_accent=True, title_caps=True,
                    title_size=10.5, title_rule="below", italic_meta=True),
    "modern": Look("Calibri", 10.5, 24, "0D6B62", "left", headline_accent=True, title_size=11.5,
                   header_rule=True),
    "minimal": Look("Arial", 9.5, 16, "5C5C58", "left", headline_accent=True, title_caps=True,
                    title_bold=False, title_size=8, title_rule="above"),
}


def _border(paragraph: Paragraph, side: str, color: str, size: int, space: int = 2) -> None:
    """Paragraph border (python-docx has no API for it). Inserted in schema order so Word opens the file cleanly."""
    pPr = paragraph._p.get_or_add_pPr()
    borders = pPr.find(qn("w:pBdr"))
    if borders is None:
        borders = OxmlElement("w:pBdr")
        pPr.insert_element_before(
            borders, "w:shd", "w:tabs", "w:suppressAutoHyphens", "w:kinsoku", "w:wordWrap",
            "w:overflowPunct", "w:topLinePunct", "w:autoSpaceDE", "w:autoSpaceDN", "w:bidi",
            "w:adjustRightInd", "w:snapToGrid", "w:spacing", "w:ind", "w:contextualSpacing",
            "w:mirrorIndents", "w:suppressOverlap", "w:jc", "w:textDirection", "w:textAlignment",
            "w:textboxTightWrap", "w:outlineLvl", "w:divId", "w:cnfStyle", "w:rPr", "w:sectPr",
            "w:pPrChange",
        )
    edge = OxmlElement(f"w:{side}")
    for key, value in {"val": "single", "sz": str(size), "space": str(space), "color": color}.items():
        edge.set(qn(f"w:{key}"), value)
    borders.append(edge)


def _link(paragraph: Paragraph, url: str, text: str):
    """A clickable hyperlink run. Returns the run so the caller can format it."""
    r_id = paragraph.part.relate_to(url, RT.HYPERLINK, is_external=True)
    link = OxmlElement("w:hyperlink")
    link.set(qn("r:id"), r_id)
    run = paragraph.add_run(text)
    link.append(run._r)
    paragraph._p.append(link)
    return run


class _SectionWriter(HTMLParser):
    """Walks one section's HTML and writes Word paragraphs."""

    def __init__(self, doc, look: Look, style: Style, text_width: Emu):
        super().__init__(convert_charrefs=True)
        self.doc, self.look, self.style, self.text_width = doc, look, style, text_width
        self.para: Paragraph | None = None
        self.empty = True
        self.bold = self.italic = self.code = 0
        self.href: str | None = None
        self.lists: list[str] = []
        self.in_li = 0
        self.in_head = self.in_title = self.in_date = False
        self.after_head = False  # the paragraph right after a heading is the organisation line
        self.meta = False  # inside that organisation line

    def _paragraph(self, style: str | None = None, space_after: float = 2) -> Paragraph:
        self.para = self.doc.add_paragraph(style=style)
        self.para.paragraph_format.space_after = Pt(space_after)
        if self.style.body_align == "justify" and not self.in_head:
            self.para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        self.empty = True
        return self.para

    def handle_starttag(self, tag, attrs):
        cls = dict(attrs).get("class", "")
        if tag == "div" and cls == "entry-head":
            self.in_head = True
            p = self._paragraph(space_after=0)
            p.paragraph_format.space_before = Pt(5)
            p.paragraph_format.keep_with_next = True
            if self.style.dates == "right":
                p.paragraph_format.tab_stops.add_tab_stop(self.text_width, WD_TAB_ALIGNMENT.RIGHT)
        elif tag == "h3":
            if not self.in_head:
                self._paragraph()
            self.in_title = True
        elif tag == "span" and cls == "entry-date":
            if self.para is None:
                self._paragraph()
            if self.style.dates == "right":
                self.para.add_run("\t")
            elif not self.empty:
                self.para.add_run().add_break()
            self.in_date = True
        elif tag == "p" and not self.in_li:
            p = self._paragraph()
            if self.after_head:
                p.paragraph_format.keep_with_next = True
                self.meta = True
        elif tag in ("ul", "ol"):
            self.lists.append(tag)
        elif tag == "li":
            kind = "List Number" if self.lists and self.lists[-1] == "ol" else "List Bullet"
            level = min(len(self.lists), 3)
            self._paragraph(kind if level == 1 else f"{kind} {level}", space_after=1)
            self.in_li += 1
        elif tag in ("strong", "b"):
            self.bold += 1
        elif tag in ("em", "i"):
            self.italic += 1
        elif tag == "code":
            self.code += 1
        elif tag == "a":
            self.href = dict(attrs).get("href")
        elif tag == "br" and self.para is not None:
            self.para.add_run().add_break()
        if tag not in ("div", "h3", "span", "strong", "b", "em", "i", "code", "a", "br"):
            self.after_head = False

    def handle_endtag(self, tag):
        if tag == "div" and self.in_head:
            self.in_head = False
            self.after_head = True
            self.para = None
        elif tag == "h3":
            self.in_title = False
            if not self.in_head:
                self.para = None
        elif tag == "span" and self.in_date:
            self.in_date = False
        elif tag == "p" and not self.in_li:
            self.para = None
            self.meta = False
        elif tag in ("ul", "ol") and self.lists:
            self.lists.pop()
        elif tag == "li":
            self.in_li -= 1
            self.para = None
        elif tag in ("strong", "b"):
            self.bold -= 1
        elif tag in ("em", "i"):
            self.italic -= 1
        elif tag == "code":
            self.code -= 1
        elif tag == "a":
            self.href = None

    def handle_data(self, data):
        text = re.sub(r"\s+", " ", data)
        if self.para is None:
            if not text.strip():
                return
            self._paragraph()
        if self.empty:
            text = text.lstrip()
        if not text:
            return
        run = _link(self.para, self.href, text) if self.href else self.para.add_run(text)
        self.empty = False

        font, look = run.font, self.look
        if self.in_title:
            font.bold = True
            font.size = Pt(look.size + 0.5)
        if self.bold:
            font.bold = True
        if self.italic:
            font.italic = True
        if self.code:
            font.name = "Consolas"
        if self.in_date or self.meta:
            font.color.rgb = MUTED
            font.size = Pt(look.size - 0.5)
            if look.italic_meta:
                font.italic = True


def render_docx(resume: Resume, template: str, page_size: str = "A4", style: Style | None = None) -> bytes:
    if template not in available_templates():
        raise ValueError(f"Unknown template: {template!r}")
    if page_size not in PAGE_SIZES:
        raise ValueError(f"Unknown page size: {page_size!r}")
    style = style or Style()
    look = LOOKS.get(template, LOOKS["classic"])
    accent_hex = (ACCENTS[style.accent] or f"#{look.accent}").lstrip("#").upper()
    accent = RGBColor.from_string(accent_hex)

    doc = Document()
    doc.core_properties.author = resume.name
    doc.core_properties.title = f"{resume.name} Resume"

    section = doc.sections[0]
    if page_size == "A4":
        section.page_width, section.page_height = Mm(210), Mm(297)
    else:
        section.page_width, section.page_height = Inches(8.5), Inches(11)
    for side in ("left_margin", "right_margin", "top_margin", "bottom_margin"):
        setattr(section, side, Mm(16))
    text_width = section.page_width - section.left_margin - section.right_margin

    normal = doc.styles["Normal"]
    normal.font.name = look.font
    normal.font.size = Pt(look.size)
    normal.font.color.rgb = TEXT
    normal.element.rPr.rFonts.set(qn("w:eastAsia"), look.font)
    normal.paragraph_format.space_before = Pt(0)
    normal.paragraph_format.space_after = Pt(2)
    normal.paragraph_format.line_spacing = 1.15

    header_align = ALIGN[look.header_align if style.header_align == "default" else style.header_align]
    title_align = ALIGN["left" if style.title_align == "default" else style.title_align]

    p = doc.add_paragraph()
    p.alignment = header_align
    run = p.add_run(resume.name)
    run.font.size = Pt(look.name_size)
    run.font.bold = look.title_bold
    if look.name_accent:
        run.font.color.rgb = accent
    last = p

    if resume.headline:
        p = doc.add_paragraph()
        p.alignment = header_align
        run = p.add_run(resume.headline)
        run.font.size = Pt(look.size + 1.5)
        if look.headline_accent:
            run.font.color.rgb = accent
        last = p

    if resume.contacts:
        p = doc.add_paragraph()
        p.alignment = header_align
        p.paragraph_format.space_before = Pt(3)
        run = p.add_run(" | ".join(resume.contacts))
        run.font.size = Pt(look.size - 1)
        run.font.color.rgb = MUTED
        last = p
    if look.header_rule:
        _border(last, "bottom", accent_hex, 12, space=6)

    for sec in resume.sections:
        p = doc.add_paragraph()
        p.alignment = title_align
        p.paragraph_format.space_before = Pt(12)
        p.paragraph_format.space_after = Pt(4)
        p.paragraph_format.keep_with_next = True
        run = p.add_run(sec.title)
        run.font.size = Pt(look.title_size)
        run.font.bold = look.title_bold
        run.font.all_caps = look.title_caps  # display only: the text itself stays "Experience" for ATS
        run.font.color.rgb = accent
        if look.title_rule == "below":
            _border(p, "bottom", accent_hex, 6)
        elif look.title_rule == "above":
            _border(p, "top", "C9C9C4", 4, space=6)

        writer = _SectionWriter(doc, look, style, text_width)
        writer.feed(sec.html)
        writer.close()

    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
